# Generated by Django 4.2.14 on 2024-08-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_weight', models.FloatField(blank=True, null=True)),
                ('exit_weight', models.FloatField(blank=True, null=True)),
                ('net_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
